title: Git hub Lab Intro C programing
tagline: new Couse
description: git hub lab learning with c programing learning
template:
  repo: git-hub-lab-template
  name: git-hub-lab
  description: 'This is use to c programing languages with git hub  '
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
    action_id: '#sky'
  - type: closeIssue
steps:
  - title: Assign yourself
    description: "Unassigned issues don't have owners to look after them. When you’re assigned to an issue or pull request, it tells repository visitors and contributors that you'll be facilitating the conversation or task \U0001F4AA.  ⌨️ Activity On the right side of the screen, under the \"Assignees\" section, click the gear icon and select yourself For a printable version of the steps in this course, check out the Quick Reference Guide."
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
        issue: ''
        action_id: ''
      - type: createPullRequest
  - title: Turn on GitHub Pages
    actions:
      - type: createIssue
        title: A new issue
        body: a-response-file.md
      - type: mergePullRequest
    description: "You're now the proud manager of this issue! Now that you've assigned yourself, people who drop by know that they're welcome to participate, but you'll be carrying this issue across the finish line. \U0001F60E.  Let's use GitHub Pages Now, on to business! GitHub Pages allow you to serve a static site from a repository. We've filled this repository with some site content, but the rendered site isn't visible right now. Let's change that.  ⌨️ Activity: Enable GitHub Pages Click on the Settings tab in this repository Scroll down to the \"GitHub Pages\" section From the \"Source\" drop down, select master branch Note: Even though you'll see an option to choose a theme, do not apply a theme at this point. We've protected the code so you can't make unintended changes. You'll have the opportunity to apply a theme when the course is completed."
    event: commit_comment
  - title: Close an issue
    actions:
      - type: createIssue
        title: A new issue
        body: a-response-file.md
    description: >-
      You turned on GitHub Pages!  Your site is now visible to the public. Check
      it out at https://kavindyasinthasilva.github.io/github-slideshow/.  Now
      that you’ve completed the tasks in this issue, it's time to close it!
      Closing an issue tells other contributors that this particular
      conversation or task has come to an end.  ⌨️ Activity Click the Close
      issue button below
  - title: commit
    actions:
      - type: createIssue
        title: A new issue
        body: a-response-file.md
    description: add new commit and change name
  - title: pull requests
    actions:
      - type: createIssue
        title: A new issue
        body: a-response-file.md
    description: 'click merge pull request '
  - title: last step
    actions:
      - type: createIssue
        title: A new issue
        body: a-response-file.md
